[workspace]
members = [
#	"vendor/token-2022-solana-spl",
	"vendor/token-2022-solana-spl/clients/cli",
	"vendor/token-2022-solana-spl/clients/rust", #omitted from workspace until a real client is generated
	"vendor/token-2022-solana-spl/clients/rust-legacy",
	"vendor/token-2022-solana-spl/confidential-transfer/ciphertext-arithmetic",
		"vendor/token-2022-solana-spl/confidential-transfer/elgamal-registry",
	"vendor/token-2022-solana-spl/confidential-transfer/proof-extraction",
		"vendor/token-2022-solana-spl/confidential-transfer/proof-generation",
		"vendor/token-2022-solana-spl/confidential-transfer/proof-tests",
		"vendor/token-2022-solana-spl/program",
    "account-decoder",
    "accounts-bench",
    "accounts-cluster-bench",
    "banking-bench",
    "banks-client",
    "banks-interface",
    "banks-server",
    "bench-streamer",
    "bench-tps",
    "bloom",
    "bucket_map",
    "clap-utils",
    "clap-v3-utils",
    "cli",
    "cli-config",
    "cli-output",
    "client",
    "client-test",
    "core",
    "dos",
    "download-utils",
    "entry",
    "faucet",
    "frozen-abi",
    "genesis",
    "genesis-utils",
    "geyser-plugin-interface",
    "geyser-plugin-manager",
    "gossip",
    "install",
    "keygen",
    "ledger",
    "ledger-tool",
    "local-cluster",
    "log-analyzer",
    "logger",
    "measure",
    "memory-management",
    "merkle-root-bench",
    "merkle-tree",
    "metrics",
    "net-shaper",
    "net-utils",
    "notifier",
    "perf",
    "poh",
    "poh-bench",
    "program-test",
    "programs/address-lookup-table",
    "programs/address-lookup-table-tests",
    "programs/bpf-loader-tests",
    "programs/bpf_loader",
    "programs/bpf_loader/gen-syscall-list",
    "programs/compute-budget",
    "programs/config",
    "programs/ed25519-tests",
    "programs/stake",
    "programs/vote",
    "programs/zk-token-proof",
    "pubsub-client",
    "quic-client",
    "rayon-threadlimit",
    "rbpf-cli",
    "remote-wallet",
    "rpc",
    "rpc-client",
    "rpc-client-api",
    "rpc-client-nonce-utils",
    "rpc-test",
    "runtime",
    "runtime/store-tool",
    "sdk",
    "sdk/cargo-build-bpf",
    "sdk/cargo-build-sbf",
    "sdk/cargo-test-bpf",
    "sdk/cargo-test-sbf",
    "sdk/gen-headers",
    "send-transaction-service",
    "stake-accounts",
    "storage-bigtable",
    "storage-proto",
    "streamer",
    "sys-tuner",
    "test-validator",
    "thin-client",
    "tokens",
    "tpu-client",
    "transaction-dos",
    "transaction-status",
    "udp-client",
    "upload-perf",
    "validator",
    "version",
    "watchtower",
    "zk-token-sdk",
]

exclude = [
    "programs/sbf",
]

# This prevents a Travis CI error when building for Windows.
resolver = "2"

# for details, see https://github.com/solana-labs/crossbeam/commit/fd279d707025f0e60951e429bf778b4813d1b6bf
[patch.crates-io]
crossbeam-epoch = { git = "https://github.com/solana-labs/crossbeam", rev = "fd279d707025f0e60951e429bf778b4813d1b6bf" }



[workspace.package]
 authors = ["Anza Maintainers <maintainers@anza.xyz>"]
 repository = "https://github.com/solana-program/token-2022"
 homepage = "https://solana-program.com"
 license = "Apache-2.0"
 edition = "2021"

 [workspace.lints.rust.unexpected_cfgs]
 level = "warn"
 check-cfg = [
     'cfg(target_os, values("solana"))',
     'cfg(feature, values("frozen-abi", "no-entrypoint", "custom-heap", "custom-panic"))',
 ]
