[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-gossip"
description = "Blockchain, Rebuilt for Scale"
version = "1.15.1"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-gossip"

[dependencies]
bincode = "1.3.3"
bv = { version = "0.11.1", features = ["serde"] }
clap = "2.33.1"
crossbeam-channel = "0.5"
flate2 = "1.0"
indexmap = { version = "1.9", features = ["rayon"] }
itertools = "0.10.5"
log = "0.4.17"
lru = "0.7.7"
matches = "0.1.9"
num-traits = "0.2"
rand = "0.7.0"
rand_chacha = "0.2.2"
rayon = "1.5.3"
serde = "1.0.144"
serde_bytes = "0.11"
serde_derive = "1.0.103"
solana-bloom = { path = "../bloom", version = "*" }
solana-clap-utils = { path = "../clap-utils", version = "*" }
solana-client = { path = "../client", version = "*" }
solana-entry = { path = "../entry", version = "*" }
solana-frozen-abi = { path = "../frozen-abi", version = "*" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "*" }
solana-ledger = { path = "../ledger", version = "*" }
solana-logger = { path = "../logger", version = "*" }
solana-measure = { path = "../measure", version = "*" }
solana-metrics = { path = "../metrics", version = "*" }
solana-net-utils = { path = "../net-utils", version = "*" }
solana-perf = { path = "../perf", version = "*" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "*" }
solana-runtime = { path = "../runtime", version = "*" }
solana-sdk = { path = "../sdk", version = "*" }
solana-streamer = { path = "../streamer", version = "*" }
solana-thin-client = { path = "../thin-client", version = "*" }
solana-tpu-client = { path = "../tpu-client", version = "*", default-features = false }
solana-version = { path = "../version", version = "*" }
solana-vote-program = { path = "../programs/vote", version = "*" }
thiserror = "1.0"

[dev-dependencies]
num_cpus = "1.13.1"
regex = "1"
serial_test = "0.9.0"

[build-dependencies]
rustc_version = "0.4"

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bin]]
name = "solana-gossip"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
