[package]
name = "solana-transaction-status"
version = "1.15.1"
description = "Solana transaction status types"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-transaction-status"
license = "Apache-2.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
base64 = "0.13.0"
bincode = "1.3.3"
borsh = "0.9.1"
bs58 = "0.4.0"
lazy_static = "1.4.0"
log = "0.4.17"
serde = "1.0.144"
serde_derive = "1.0.103"
serde_json = "1.0.83"
solana-account-decoder = { path = "../account-decoder", version = "*" }
solana-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "*" }
solana-sdk = { path = "../sdk", version = "*"  }
spl-associated-token-account = { version = "*", features = ["no-entrypoint"] }
spl-memo = { version = "*", features = ["no-entrypoint"] }
spl-token = { version = "*", features = ["no-entrypoint"] }
spl-token-2022 = { version = "*", path="../vendor/token-2022-solana-spl/program", features = ["no-entrypoint"] }
thiserror = "1.0"
# solana-ledger = {path="../ledger" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
