[package]
name = "solana-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
version = "1.15.1"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-tokens"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.15.0"
csv = "1.1.6"
ctrlc = { version = "3.2.3", features = ["termination"] }
indexmap = "1.9.1"
indicatif = "0.17.1"
pickledb = { version = "0.5.1", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
solana-account-decoder = { path = "../account-decoder", version = "*" }
solana-clap-utils = { path = "../clap-utils", version = "*" }
solana-cli-config = { path = "../cli-config", version = "*" }
solana-remote-wallet = { path = "../remote-wallet", version = "*" }
solana-rpc-client = { path = "../rpc-client", version = "*" }
solana-rpc-client-api = { path = "../rpc-client-api", version = "*" }
solana-sdk = { path = "../sdk", version = "*" }
solana-transaction-status = { path = "../transaction-status", version = "*" }
solana-version = { path = "../version", version = "*" }
spl-associated-token-account = { version = "*" }
spl-token = { version = "*", features = ["no-entrypoint"] }
tempfile = "3.3.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
solana-logger = { path = "../logger", version = "*" }
solana-streamer = { path = "../streamer", version = "*" }
solana-test-validator = { path = "../test-validator", version = "*" }
